name: Artifacts (Dagger)

on:
  push:
    tags:
      - v2.[0-9]+.[0-9]+

jobs:
  binaries:
    name: Binaries
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dagger
        uses: dagger/dagger-for-github@v4
        with:
          cmds: |
            project update
            do release github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
